dictionary:
  scm:
    branches:
    - master
    - development
  istio:
    enabled: true
  build_configs:
    enabled: true
  deployment_configs:
    enabled: true
    force_update: false
  profile:
  - stage
  - profile

  node_selector:
    foo:
    - bar
    - biz

    profile:
    - prod
    - stage