
pipeline:
  name: nodejs
  identifiers: # unused
  - package.json
  istioConfigs:
    skip: true
  buildConfigs:
    imagestream: s2i-nodejs:alpine
    env:
    - name: npm_config_registry
      value: ${npm_config_registry}
    - name: npm_config_disturl
      value: https://npm.taobao.org/dist/
    - name: npm_config_phantomjs_cdnurl
      value: https://npm.taobao.org/dist/phantomjs/
    - name: npm_config_phantomjs_cdnurl
      value: https://npm.taobao.org/dist/phantomjs/
    - name: npm_config_electron_mirror
      value: https://npm.taobao.org/mirrors/electron/
    - name: npm_config_sass_binary_site
      value: https://npm.taobao.org/mirrors/node-sass/
    - name: BUILD_SCRIPT
      value: |
        nid="npm install --only=dev"
        ni="npm install"
        nrb="npm run build:dev"
        for cmd in "${nid}" "${ni}" "${nrb}" ;
          do
            echo "${cmd} 开始"
            ${cmd}
            if [[ $? == 0 ]]; then
              echo "$cmd Successful."
            else
              echo "$cmd Failed!"
              exit 1
            fi
        done
  deploymentConfigs:
    healthEndPoint: http://localhost:8080/
    env:
    - name: NODE_ENV
      value: ${profile}
    - name: HOST
      value: 0.0.0.0
    - name: PORT
      value: 8080
    - name: project
      value: ${project}
    - name: RUN_SCRIPT
      value: |
        npm run build:dev
        if [[ $? == 0 ]]; then
          echo "npm run build:dev Successful."
        else
          echo "npm run build:dev Failed!"
          exit 1
        fi
        npm run start
